title: Micaella Nuqui
logo: /personalwebsite/myprofile.jpg
show_downloads: true
theme: jekyll-theme-minimal
style: |
  <style>
    /* Replace ".logo" with the appropriate class or ID for your logo */
    .logo {
      width: 150px; 
      height: 150px; 
    }
  </style>
